### ISSUE TITLE
ProcessTimedOutException on large 7Zip archives

### ISSUE THREAD

**Issue by lasselehtinen** [Gemorroj/Archive7z#16]
See issue below utilizing this package for extracting files from 7z archives. Would be possible to make to Symfony process timeout configurable [as described here](https://symfony.com/doc/current/components/process.html#process-timeout)?

https://github.com/wapmorgan/UnifiedArchive/issues/10

**Comment by Gemorroj** [comment]
as hotfix, i can recommend something like this code:
```php
<?php
use Archive7z\Archive7z;
use Symfony\Component\Process\Process;

class MyArchive7z extends Archive7z
{
    protected function execute(Process $process)
    {
        $process->setTimeout(3600);
        return parent::execute($process);
    }
}
```

**Comment by Gemorroj** [comment]
https://symfony.com/blog/new-in-symfony-4-2-wait-until-processes-are-ready
