### ISSUE TITLE
Need help with installation

### ISSUE THREAD

**Issue by HonzaSTECH** [Gemorroj/Archive7z#25]
Hi. Sorry for bothering you all, but I need some help with installing Archive7z.

My website runs on a 3rd party web hosting service. I uploaded all the files and it seems to be working fine except for one problem: It can't find the 7zip executable.

In `Archive7zTrait.php`, I changed the path specified in `$binary7zNix`, because there would be some problems with directory permissions, so I now just need the executable to upload. But I can't find a way to get it. I'm using Windows on my PC and I don't have access to the command line of the Linux server, that is used by the hosting service.

Could somebody please send me the executable, so I can upload it? Or if you think that this won't be enough, can you help me in any other way?

**Comment by Gemorroj** [comment]
Hi. To change the path to 7z better use second parameter of Archive7z constructor.
```php
$obj = new Archive7z('somefile.7z', '/path/to/binary/7z');
```
You can try this [p7zip.zip](https://github.com/Gemorroj/Archive7z/files/6673275/p7zip.zip) binaries (builded from https://github.com/jinfeihan57/p7zip/archive/v17.04.tar.gz). But I don't know if it will help.

**Comment by HonzaSTECH** [comment]
Thanks a lot. Fixed the issue for me. :)
