### ISSUE TITLE
Cant not find 7za because I install p7zip with opkg

### ISSUE THREAD

**Issue by flyshu** [Gemorroj/Archive7z#35]
Hi, thanks for very nice, useful package.

I installed p7zip from OPKG,so the Binary of 7-zip is in /opt/bin/7za, the Archive7z can not find Binary 

How can I fix it ? Thanks.

**Comment by Gemorroj** [comment]
@flyshu hi. you can use the second parameter in the Archive7z constructor, for example.
```php
$obj = new Archive7z('path_to_7z_file.7z', '/opt/bin/7za');
```

**Comment by flyshu** [comment]
> @flyshu hi. you can use the second parameter in the Archive7z constructor, for example.
> 
> ```
> $obj = new Archive7z('path_to_7z_file.7z', '/opt/bin/7za');
> ```

It's OK. Thanks.
