### ISSUE TITLE
Got $entry->getPackedSize() only for first file

### ISSUE THREAD

**Issue by wapmorgan** [Gemorroj/Archive7z#5]
Hi. Tried library and faced this issue.
```php
                $this->seven_zip = new \Archive7z\Archive7z($filename);
                foreach ($this->seven_zip->getEntries() as $entry) {
                    var_dump($entry->getPackedSize());
                }
```
It returns only first file value. Also, that's value for all array, not for specified file.
```
string(5) "10584"
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
```

**Comment by Gemorroj** [comment]
Скорее тут проблема в выдаче Packed Size самим 7-zip.
Для латиницы Packed Size выдается нормально. А для кириллицы пустое значение.
Создал баг на форуме 7-zip.
https://sourceforge.net/p/sevenzip/discussion/45797/thread/c8c8b533/

**Comment by wapmorgan** [comment]
Ок, невозможно.

**Comment by Gemorroj** [comment]
Судя по ответу Игоря Павлова (разработчика 7-zip), проблема не в названии файлов, а в структуре их хранения. Packed Size выдается только для первого файла внутри solid (не знаю как перевести) блока.
