### ISSUE TITLE
Add support zip, gzip, bzip etc...

### ISSUE THREAD

**Issue by Gemorroj** [Gemorroj/Archive7z#8]

**Comment by violuke** [comment]
Maybe check out [wapmorgan/UnifiedArchive](https://github.com/wapmorgan/UnifiedArchive) as it provides support for multiple formats and uses this under the hood for its 7z support.

**Comment by Gemorroj** [comment]
Yes, I am familiar with @wapmorgan 😃 
These are independent projects, and even if the functionality will be duplicated, there is nothing to worry about.

**Comment by wapmorgan** [comment]
Archive7z and UnifiedArchie are projects with fundamental difference. UA uses php-level extensions to provide all functionality (excluding wrapper for lzw compressed tar's), Archive7z calls to system-level utility. Both projects have pros and cons.
